//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZavrsniProjekatSaloni.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.Articles = new HashSet<Article>();
        }
    
        public int CategoryId { get; set; }

        [Required(ErrorMessage = "Polje je obavezno!")]
        [StringLength(50, ErrorMessage = "Ime kategorije ne sme imati vise od 50 karaktera")]
        [Display(Name = "Ime kategorije")]
        [Remote("IsCategoryNameExist", "Categories", AdditionalFields = "CategoryId", ErrorMessage = "Ime kategorije je zauzeto")]
        public string CategoryName { get; set; }

        [Required(ErrorMessage = "Polje je obavezno!")]
        [StringLength(200, ErrorMessage = "Opis kategorije ne sme imati vise od 200 karaktera")]
        [Display(Name = "Opis")]
        [Remote("IsCategoryDescriptionExist", "Categories", AdditionalFields = "CategoryId", ErrorMessage = "Opis kategorije je zauzet")]
        public string CategoryDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article> Articles { get; set; }
    }
}
