//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZavrsniProjekatSaloni.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Salon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Salon()
        {
            this.Articles = new HashSet<Article>();
        }
    
        public int SalonId { get; set; }

        [Required(ErrorMessage = "Polje je obavezno!")]
        [Display(Name = "Ime")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Polje je obavezno!")]
        [Display(Name = "Vlasnik")]
        public string Owner { get; set; }
        [Required(ErrorMessage = "Polje je obavezno!")]
        [Display(Name = "Adresa")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Polje je obavezno!")]
        [Display(Name = "Broj telefona")]
        public int PhoneNumber { get; set; }
        [Required(ErrorMessage = "Polje je obavezno!")]
        [Display(Name = "Mail adresa")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Polje je obavezno!")]
        [Display(Name = "Web stranica")]
        public string WebPage { get; set; }
        [Required(ErrorMessage = "Polje je obavezno!")]
        [Display(Name = "PIB")]
        public int TIN { get; set; }
        [Required(ErrorMessage = "Polje je obavezno!")]
        [Display(Name = "Bankovni racun")]
        public long BankAccountNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article> Articles { get; set; }
    }
}
