//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZavrsniProjekatSaloni.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Bills = new HashSet<Bill>();
        }
           
        public int UserId { get; set; }
        [Required(ErrorMessage ="Polje je obavezno!")]
        [Display(Name = "Korisnicko ime")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Polje je obavezno!")]
        [Display(Name = "Lozinka")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Polje je obavezno!")]
        [Display(Name = "Ime")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Polje je obavezno!")]
        [Display(Name = "Prezime")]
        public string LastName { get; set; }
       
        public int RoleId { get; set; }
        [Required(ErrorMessage = "Polje je obavezno!")]
        [Display(Name = "Adresa")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Polje je obavezno!")]
        [Display(Name = "Mail adresa")]
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
        
        public virtual Role Role { get; set; }
    }
}
